config/routes.rb
MongoSrc::Application.routes.draw do

  match 'space/:s/wish/new' =>'wishes#new'
  
  get 'follow/fo/:id', :action=>'fo',:controller=>'follow'
  get 'follow/unfo/:id', :action=>'unfo',:controller=>'follow'
  get 'follow/fo_tag/:tag', :action=>'fo_tag', :controller=>'follow', :as=>'fo_tag'
  get 'follow/unfo_tag/:tag', :action=>'unfo_tag', :controller=>'follow',:as=>'unfo_tag'

  get "/public-timeline", :action=>'publictimeline',:controller=>'index',:as=>'publictimeline'
  
  delete '/timeline/:id',:controller=>'timeline', :action=>'del'

  get '/reg', :controller=>'user',:action=>'reg'
  match "auth/:provider/callback", :to => "user#auth_callback"  

  resources :wishes,:except=>:new do
    collection do
      post 'comment'
      delete 'comment'
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
    end
  end
  
  resources :users, :controller=>'user',:only=>[:create,:show] do 
    resources :spaces
    member do
    end
  end
  
  resources :spaces do
    collection do
      post 'comment'
      delete 'comment'
    end  
  end
  
  resources :topics, :except => [:destroy] do
    resources :replies, :except => [:destroy]
    collection do
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get 'mine', :action=>'mine',:as=>:mine
      get 'replied', :action=>'replied', :as=>:replied
      get 'marked', :action=>'marked', :as=>:marked
      get 'interested', :action=>'interested', :as=>:interested
    end
    
    member do
      get :mark
      get :unmark
    end
    
  end
  
  resources :replies
  
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end









  root :to => "index#index", :as=>'index'


end

app/views/share/_comments.haml
#comments
  -if @comments&&@comments_counter>0
    %h3=@comments_counter.to_s+'条评论'
    -@comments.each do |comment|
      %p
        =comment.created_at
        =link_to comment.user_name,user_url(comment.user_id)
        -if comment.user_id==session[:user_id]||@isowner
          =link_to '删除',{:action=>'comment',:cid=>comment.id},{:confirm=>'确认删除？',:method=>:delete}
      %p=comment.content
      %hr
  -else
    %h3 还没有评论，快来抢沙发吧
  =form_tag :action=>'comment' do
    我要评论：
    %br
    =text_area_tag(:comment, "", :size => "60x6") 
    %br
    = submit_tag "放上去"


app/views/share/_error_messages.haml
.error
  - object.errors.full_messages.each do |message|
    .item= message

app/views/share/_header.haml

#user-info
  .avatar=avatar_url @user
  .info
    %ul
      %li=link_to @user.name+'的主页',user_url(@user.id)
      %li=link_to '愿望空间',user_spaces_url(@user)
    %h1=@h1

app/views/share/_paginate.haml
- total_page = collection.total_pages
- current_page = collection.current_page
- per_page = collection.per_page
- remote ||= false
- if total_page > 1
  %table.paginate
    %tr
      %td.prev
        - if current_page != 1
          - prev_page = current_page - 1
          = link_to t('.prev_page'), url_for(:page => prev_page), :class => 'prev button', :remote => remote

      %td.pages
        - unless defined? hide_page and hide_page
          - pages = [1, current_page, total_page]
          - 3.times {|n| pages << current_page - n if current_page - n > 1} 
          - 3.times {|n| pages << current_page + n if current_page + n < total_page} 
          - pages = pages.sort.uniq
          - pages.inject(0) do |prev, page|
            - if page - prev > 1
              %span.dot ...
            - if page != current_page
              = link_to page, url_for(:page => page), :class => 'button', :remote => remote
            - else
              %span.current_page.button-like= page
            - page
          

      %td.next
        - if current_page < total_page
          = link_to t('.next_page'), url_for(:page => current_page + 1), :class => 'next button', :remote => remote