config/routes.rb
MongoSrc::Application.routes.draw do

  match 'space/:s/wish/new' =>'wishes#new'
  
  get 'follow/fo/:id', :action=>'fo',:controller=>'follow'
  get 'follow/unfo/:id', :action=>'unfo',:controller=>'follow'
  get 'follow/fo_tag/:tag', :action=>'fo_tag', :controller=>'follow', :as=>'fo_tag'
  get 'follow/unfo_tag/:tag', :action=>'unfo_tag', :controller=>'follow',:as=>'unfo_tag'

  get "/public-timeline", :action=>'publictimeline',:controller=>'index',:as=>'publictimeline'
  
  delete '/timeline/:id',:controller=>'timeline', :action=>'del'

  get '/reg', :controller=>'user',:action=>'reg'
  match "auth/:provider/callback", :to => "user#auth_callback"  

  resources :wishes,:except=>:new do
    collection do
      post 'comment'
      delete 'comment'
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
    end
  end
  
  resources :users, :controller=>'user',:only=>[:create,:show] do 
    resources :spaces
    member do
    end
  end
  
  resources :spaces do
    collection do
      post 'comment'
      delete 'comment'
    end  
  end
  
  resources :topics, :except => [:destroy] do
    resources :replies, :except => [:destroy]
    collection do
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get 'mine', :action=>'mine',:as=>:mine
      get 'replied', :action=>'replied', :as=>:replied
      get 'marked', :action=>'marked', :as=>:marked
      get 'interested', :action=>'interested', :as=>:interested
    end
    
    member do
      get :mark
      get :unmark
    end
    
  end
  
  resources :replies
  
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end









  root :to => "index#index", :as=>'index'


end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include StringExtensions
  
  field :title
  field :content
  field :tags, :type => Array
  field :closed, :type => Boolean
  field :replies_count, :type => Integer, :default => 0
  field :last_replied_at, :type => Time
  field :marker_ids, :type => Array
  field :replier_ids, :type => Array
  belongs_to :last_replied_by, :class_name=>'User'
  
  attr_accessible :title, :content, :tags
  
  validates_presence_of :title, :content
  validates_length_of :title, :maximum => 100
  validates_length_of :tags, :maximum => 5
  validates_length_of :tags, :minimum =>1
  
  embeds_many :replies, :validate => false, :dependent => :delete
  belongs_to :user
  
  
  
  def tags=(value)
    if value.is_a? String
      write_attribute :tags, parse_tags_from_string(value)
    else
      write_attribute :tags, value.uniq
    end
  end
  
  def tags_string
    return tags.join(' ') unless tags.blank?
  end
  
  def reply_by(user)
    return if self.user_id == user.id
    collection.update({:_id => self.id, :replier_ids => {"$ne" => user.id}},
      {"$push" => {:replier_ids => user.id}})
  end
  
  def mark_by(user)
    collection.update({:_id => self.id, :marker_ids => {"$ne" => user.id}},
      {"$push" => {:marker_ids => user.id}})
  end

  def unmark_by(user)
    collection.update({:_id => self.id},
      {"$pull" => {:marker_ids => user.id}})
  end
  
end

app/controllers/topics_controller.rb
#encoding:utf-8

class TopicsController < ApplicationController
  respond_to :html,:rss, :only => [:index, :tagged]
  def index
    @current='index'
    @topics=Topic.all.desc(:last_replied_at)
    set_page_title('茶馆 ')
    @wishes=Wish.get_tagged_wishes('',session[:user_id],session[:user_name])
  end
  
  def show
    @topic=Topic.find(params[:id])
    @author=@topic.user
    @reply=Reply.new
    @replies=@topic.replies.all
    @relate_topics=Topic.where(:tags.in=>@topic.tags.to_a)
    @relate_wishes=Wish.where(:tags.in=>@topic.tags.to_a)
  end 
  
  def new
    @topic=Topic.new
  end
  
  def create
    @topic=Topic.new(params[:topic])
    @topic.user_id=session[:user_id]
    if @topic.save
      flash[:success]='成功发起话题'
      redirect_to topics_url
    else
      render :new
    end
  end
  
  def edit
    @topic=Topic.find(params[:id])
    render_404 and return unless @topic.user_id==session[:user_id]
  end
  
  def update
    @topic=Topic.find(params[:id])
    render_404 and return unless @topic.user_id==session[:user_id]
    if @topic.update_attributes(params[:topic])
      flash[:success]='修改成功'
      redirect_to topic_url(@topic)
    else
      render :new
    end    
  end
  
  def tag
    @tag = params[:tag]
    @current='tag'
    @h1=@tag
    @current_user=current_user
    @wishes=Wish.get_tagged_wishes(@tag,session[:user_id],session[:user_name])
    set_page_title(@tag)
    if params[:format] == 'rss'
        @topics = Topic.where(:tags => @tag).desc(:created_at).paginate :per_page => 20, :page => params[:page]
    else
        @topics = Topic.where(:tags => @tag).desc(:last_replied_at).paginate :per_page => 20, :page => params[:page]
    end
    
    respond_with(@topics) do |format|
      format.html
      format.rss  do
        @channel_link = tagged_topics_url(:tag => @tag)
        render :topics, :layout => false
      end
      format.js { render :index, :layout => false }
    end       
  end
  
  def mine
    @current='mine'
    @topics=Topic.where(:user_id=>session[:user_id])
    render 'index'
  end
  
  def replied
    @current='replied'
    @topics=Topic.where(:replier_ids=>session[:user_id])
  end
  
  def marked
    @current='marked'
    @topics=Topic.where(:marker_ids=>session[:user_id])
  end
  
  def mark
    @topic = Topic.find params[:id]
    @topic.mark_by current_user
    respond_to do |format|
      format.html {redirect_to @topic}
      format.js
    end
  end
  
  def unmark
    @topic = Topic.find params[:id]
    @topic.unmark_by current_user
    respond_to do |format|
      format.html {redirect_to @topic}
      format.js
    end
  end
  
  def interested
    @topics=Topic.where(:tags.in=>current_user.interested_tags.to_a).desc
    @current='interested'
  end
  
  
  def destory
  
  end

  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.haml
=form_for(@topic) do |f|
  -if @topic.errors.any?
    #error_explanation
      %ul
        -@topic.errors.full_messages.each do |msg|
          %li=msg
  
  .field
    =f.label :title
    %br/
    =f.text_field :title
    %br/
    =f.label :content
    %br/
    =f.text_area :content,:size=>"70x10"
    %br
    =f.label :tags
    （至少要添加一个标签）
    %br
    = f.text_field :tags,:value=>@topic.tags_string
    .action
      =f.submit
=javascript_include_tag 'nicEdit'
:javascript
  bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
    

app/views/topics/_subnav.haml
#sub-nav
  %ul
    %li{:class=>(@current == 'index' ? :current : nil)}
      =link_to '茶馆',topics_url
    %li{:class=>(@current == 'interested' ? :current : nil)}
      =link_to '我关注的', interested_topics_url
    %li{:class=>(@current == 'mine'? :current :nil)}
      =link_to '我发起的', mine_topics_url
    %li{:class=>(@current == 'replied'? :current : nil )}
      =link_to '我回复过', replied_topics_url
    %li{:class=>(@current=='marked'? :current : nil)}
      =link_to '收藏', marked_topics_url
    -if @tag
      %li{:class=>(@current == 'tag' ? :current : nil)}
        =@tag
.clear

app/views/topics/_topics.haml
#topics
  -@topics.each do |topic|
    .topic
      .avatar=avatar_url topic.user
      .summary
        .reply_counter
          =topic.replies_count
          回复  
        .title
          =link_to topic.title, topic_url(topic)
          -if topic.user_id==session[:user_id]
            %span.del_button X
        =link_to topic.user.name, user_url(topic.user)
        创建于
        =topic.created_at
        %br
        -if topic.last_replied_by
          =link_to topic.last_replied_by.name, topic.last_replied_by
          在
          =topic.last_replied_at
          最后回复        
        .tags 
          -topic.tags.each do |tag|
            =link_to tag, tag_topics_url(:tag=>tag),:class=>'tag'

app/views/topics/edit.haml
%h1 编辑话题
=render 'form'

app/views/topics/index.haml
=render 'subnav'

-if @topics.count==0
  还没有话题，
=link_to '发起话题', new_topic_url

=render 'topics'

app/views/topics/interested.haml
=render 'subnav'

-if @topics.count==0
  还没有收藏话题，
=link_to '随便看看', topics_url

=render 'topics'

app/views/topics/mark.js.erb
$('#mark_button').replaceWith(
'<div id="unmark_button"><%=link_to '已收藏', unmark_topic_url(@topic),:remote=>true, :title=>'取消收藏？'%></div>'
)

app/views/topics/marked.haml
=render 'subnav'

-if @topics.count==0
  您还没有收藏任何话题
=link_to '看看大家在聊些什么', topics_url

=render 'topics'
            

app/views/topics/new.haml
=render 'form'

app/views/topics/replied.haml
=render 'subnav'

-if @topics.count==0
  您还没有回复任何话题
=link_to '看看大家在聊些什么', topics_url

=render 'topics'
            

app/views/topics/show.haml
%div
  .align-left.avatar
    =avatar_url @author
  #topic
    #topic-header
      %h1=@topic.title
      来自
      =link_to @author.name, user_url(@author)
      =@topic.created_at
      -if @topic.user_id==session[:user_id]
        =link_to '编辑', edit_topic_url(@topic)
  .clear-both
    #topic-content
      =rich_text @topic.content
    #tags
      -@topic.tags.each do |tag|
        =link_to tag, tag_topics_url(:tag=>tag),:class=>'tag'
    -if @topic.marker_ids.to_a.include? session[:user_id]
      #unmark_button=link_to '已收藏', unmark_topic_url(@topic),:remote=>true,:title=>'取消收藏？'
    -else
      #mark_button
        =link_to '收藏', mark_topic_url(@topic),:remote=>true
  .clear
  #replies
    -@replies.each do |reply|
      .reply
        .align-left.avatar
          =avatar_url reply.user
        .reply-content
          =link_to reply.user.name, user_url(reply.user)
          =reply.created_at
          -if reply.user_id==session[:user_id]
            =link_to '编辑', edit_topic_reply_url(@topic,reply)
          %br
          =rich_text(reply.content)
        .clear-both
    -@topic.tags.each do |tag|
      =link_to tag, tag_topics_url(:tag=>tag),:class=>'tag'
    #reply-form
      我要回复：
      =render 'replies/form'

-content_for :rside do
  =link_to '回茶馆',topics_url
  -if @relate_topics.count>0
    #relate_topics
      相关话题
      %ul
        -@relate_topics.each do |rtopic|
          %li
            =link_to rtopic.title,topic_url(rtopic)
            %span.author
            ='('+rtopic.user.name+')'
  -if @relate_wishes.count>0
    #relate_wishes
      相关愿望
      %ul
        -@relate_wishes.each do |wish|
          %li
            =link_to wish.name, wish_url(wish)

app/views/topics/tag.haml
=render 'subnav'

-if @topics.count==0
  该标签下还没有话题，
=link_to '发起话题', new_topic_url

=render 'topics'
            
-content_for :rside do
  #wish_list
    -if @wishes.count==0
      还没有标记为
      %i=@tag
      的愿望
    -else
      -if @tag
        标记了
        %i=@tag
        的愿望
      -else
        最新愿望
      %ul
        -@wishes.each do |wish|
          %li
            =link_to wish.name,wish_url(wish)
  #fo_tag_button
    -if @current_user.interested_tags.to_a.include? @tag
      已关注
      =link_to @tag,unfo_tag_url,:class=>'tag',:remote=>true,:title=>"取消关注？"
    -else
      关注
      =link_to @tag,fo_tag_url,:class=>'tag',:remote=>true

        

      

app/views/topics/unmark.js.erb
$('#unmark_button').replaceWith(
'<div id="mark_button"><%=link_to '收藏', mark_topic_url(@topic),:remote=>true%></div>'
)