config/routes.rb
MongoSrc::Application.routes.draw do

  match 'space/:s/wish/new' =>'wishes#new'
  
  get 'follow/fo/:id', :action=>'fo',:controller=>'follow'
  get 'follow/unfo/:id', :action=>'unfo',:controller=>'follow'
  get 'follow/fo_tag/:tag', :action=>'fo_tag', :controller=>'follow', :as=>'fo_tag'
  get 'follow/unfo_tag/:tag', :action=>'unfo_tag', :controller=>'follow',:as=>'unfo_tag'

  get "/public-timeline", :action=>'publictimeline',:controller=>'index',:as=>'publictimeline'
  
  delete '/timeline/:id',:controller=>'timeline', :action=>'del'

  get '/reg', :controller=>'user',:action=>'reg'
  match "auth/:provider/callback", :to => "user#auth_callback"  

  resources :wishes,:except=>:new do
    collection do
      post 'comment'
      delete 'comment'
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
    end
  end
  
  resources :users, :controller=>'user',:only=>[:create,:show] do 
    resources :spaces
    member do
    end
  end
  
  resources :spaces do
    collection do
      post 'comment'
      delete 'comment'
    end  
  end
  
  resources :topics, :except => [:destroy] do
    resources :replies, :except => [:destroy]
    collection do
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get 'mine', :action=>'mine',:as=>:mine
      get 'replied', :action=>'replied', :as=>:replied
      get 'marked', :action=>'marked', :as=>:marked
      get 'interested', :action=>'interested', :as=>:interested
    end
    
    member do
      get :mark
      get :unmark
    end
    
  end
  
  resources :replies
  
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end









  root :to => "index#index", :as=>'index'


end

app/models/comment/space.rb
class Comment::Space<Comment::Base
  embedded_in :space
  references_many :timeline, :class_name=>'Timeline::Spacecomment', :dependent=>:delete
  
  after_create :counter_inc, :update_timeline
  after_destroy :counter_dec
  
protected
  def update_timeline
    @t=space.timeline_comment.new(:user_id=>user.id,:comment_id=>self.id,
                 :space_owner=>space.user.name,:space_owner_id=>space.user.id,
                 :user_name=>user.name, :space_name=>space.name, :content=>self.content)
    @t.save
  end
  def counter_inc
    space.inc :comments_counter, 1
  end
  
  def counter_dec
    space.inc :comments_counter, -1
  end
  
end

app/models/space.rb

class Space
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, :type => String
  field :des, :type => String
  field :access, :type => String
  field :privacy
  field :allowed_users, :type=>Array
  
  attr_accessible :allowed_users, :name, :des, :privacy
  
  validates_presence_of :name, :des, :privacy
  
  references_many :wishes, :dependent => :delete
  embeds_many :comments,:dependent=>:delete,:class_name=>'Comment::Space'
  references_many :timeline, :class_name=>'Timeline::Space', :dependent=>:delete #delete
  references_many :timeline_comment, :class_name=>'Timeline::Spacecomment', :dependent=>:delete
  referenced_in :user
  referenced_in :claimed_by, :class_name=>'User'
  
  field :wishes_counter, :type=>Integer, :default=>0
  field :comments_counter, :type=>Integer, :default=>0
  
  after_create  :update_timeline
  #after_destroy :decrement_counter_cache
  
  def get_privacy
    self.privacy
  end
  
  def allowed_users=(string)
    if string.is_a? String
      write_attribute :allowed_users, parse_users_from_string(string)
    else
      write_attribute :allowed_users, string.uniq
    end
  end
  
  def allowed_users_string
    return allowed_users.join(' ') unless allowed_users.blank?
  end
  
  def get_allowed_users
    User.get_users_by_name(allowed_users)
  end
  
  def isallowed?(uid,user_name)
    return true if uid==user_id
    case privacy
    when 'onlyme'
      uid==user.id
    when 'following'
      Follow.following?(uid,user.id)
    when 'selected'
      return true if allowed_users.include?(user_name)
    when 'public'
      true    
    end
  end
  
  def get_privacy
    privacy  
  end
  
protected

  def update_timeline
    @t=timeline.new(:user_id=>user.id,:space_id=>self.id,
                 :user_name=>user.name, :space_name=>self.name)
    @t.save
  end
  
  def parse_users_from_string(string)
    users = string.split
    users.uniq
    users.map! {|user| user.gsub "/", ""}
    users.delete_if {|user| !User.user_exists_by_name?(user)}    
  end
  
end

app/models/timeline/space.rb
#encoding:utf-8

class Timeline::Space < Timeline::Base
  field :space_name
  field :user_name

  
  referenced_in :space

end

app/controllers/spaces_controller.rb
# encoding: utf-8

class SpacesController < ApplicationController
  def index
    @user=User.find(params[:user_id])
    @spaces = @user.spaces.all
    if params[:user_id].to_s==session[:user_id].to_s
      @isowner=true 
      @h1='我的愿望空间'
    else
      @h1=@user.name+' 的愿望空间'
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @wishlists }
    end
  end
  
  def show
    @space=Space.find(params[:id])
    @user=@space.user
    @isowner=true if @user.id==session[:user_id]
    @h1=@user.name+' 的空间 '+@space.name
    @wishes=@space.wishes.all
    flash[:id]=@space.id
    @comments=@space.comments.all
    @comments_counter=@space.comments_counter
    @privacy=@space.privacy
    @is_allowed=@space.isallowed?(session[:user_id],session[:user_name])
  end
  
  def new
    @space=Space.new
  end
  
  def edit
    @space = Space.find(params[:id])
    @privacy=@space.privacy
    unless owner?(@space) #hack#
      redirect_to user_spaces_url(@space.user.id)
    end
  end
  
  def update
    @space = Space.find(params[:id])
    if !owner?(@space) #try to edit others wishlist #hack#
      render_404
      return
    elsif @space.update_attributes(params[:space])
      flash[:success]='修改成功'
      redirect_to user_spaces_url(@space.user.id)
    elsif
      render :action => "edit"
    end
  end
  
  def create
    user=User.find(session[:user_id])
    @space=user.spaces.new(params[:space])
    if @space.save
      flash[:success]='成功创建空间'
      redirect_to user_spaces_url(session[:user_id])
    else
      render :new
    end
  end
  
  def destroy
    @space = Space.find(params[:id])
    if !owner?(@space) #hack#
      render_404
    else
      @space.destroy
      flash[:success]='成功删除'
      redirect_to user_spaces_url(session[:user_id])
      end
  end
  
  def comment
    if request.post?
      @space=Space.find(flash[:id])
      flash[:error]='失败，请重试' and redirect_to :back and return unless (flash[:id]||@space.isallowed?(session[:user_id],session[:user_name]))      
      @comment=@space.comments.new(:content=>params[:comment])
      @comment.user_id=session[:user_id]
      @comment.user_name=session[:user_name]
      @comment.save
      redirect_to space_url(@space)
    end
    
    if request.delete?
      redirect_to :back,:error=>'sdf' and return unless flash[:id]
      @space=Space.find(flash[:id])
      @comment=@space.comments.find(params[:cid])
      render_404 and return unless @space.user_id==session[:user_id] || 
                                   @comment.user_id==session[:user_id]
      @comment.destroy
      redirect_to space_url(@space)
    end
  
  end
  
  private
  def owner?(space)
    space.user.id==session[:user_id]
  end
  

end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.haml
-if @privacy!='selected'
  :javascript
      $(document).ready(function(){
        $('#allowed_users').hide();
      });

=form_for(@space) do |f|
  -if @space.errors.any?
    #error_explanation
      %ul
        -@space.errors.full_messages.each do |msg|
          %li=msg
  
  .field
    =f.label :name 
    =t '.name_tips'
    %br/
    =f.text_field :name
    %br/
    =f.label :des
    %br/
    =f.text_area :des
    %br
    
    =f.label :privacy
    = f.radio_button(:privacy, "public",:checked=>true) 
    = f.label(:privacy_public, "公开") 
    = f.radio_button(:privacy, "following") 
    = f.label(:privacy_following, "关注我的人") 
    = f.radio_button(:privacy, "selected") 
    = f.label(:privacy_selected, "选择用户") 
    = f.radio_button(:privacy, "onlyme") 
    = f.label(:privacy_onlyme, "只有我") 
    #allowed_users
      =f.label :allowed_users
      = f.text_field :allowed_users, :value=>@space.allowed_users_string

    .action
      =f.submit
    :javascript
      $("input[type=radio]").change(function () {
        //alert($(this).val());  
        if($(this).val()=='selected')
          $('#allowed_users').slideDown();
        else
          $('#allowed_users').slideUp();
      });
    

app/views/spaces/_no_privacy.haml
%br
- case @privacy
- when 'following'
  %p
    该空间仅对关注者开放，立刻
    =link_to '关注', {:action=>'fo', :controller=>'follow',:id=>@user.id}
- when 'onlyme'
  %p 这是一个私人空间，您无权访问
- when 'selected'
  %p 该空间仅对选定的人开放，给他发私信

app/views/spaces/_privacy.haml
-case space.privacy
-when 'onlyme'
  不对任何人开放
-when 'public'
  公开
-when 'following'
  关注的人
-when 'selected'
  -if space.allowed_users.count>0
    对
    -space.get_allowed_users.each do |user|
      =link_to user.name, user_url(user)
    开放
  -else
    不对任何人开放

app/views/spaces/edit.haml
%h1 编辑空间

= render 'form'

= link_to '放弃修改', @wishlist
=' | '
= link_to '我的心愿单', user_spaces_url(session[:user_id])

app/views/spaces/index.haml
=render 'share/header'

- if @isowner
  - unless @spaces && @spaces.count>0
    您还没有创建愿望空间，
    =link_to '点此创建您的第一个空间', new_space_url

  - else
    =link_to '创建新的空间', new_space_url
    %br/
-else
  他还没有创建空间
- @spaces.each do |s|
  名称：
  =link_to s.name, space_url(s)
  %br/
  -if s.wishes_counter>0
    =s.wishes_counter
    个愿望
  -else
    这个空间还没有愿望
  %br
  权限：
  =render :partial=>'privacy', :locals=>{:space=>s}
  %br
  描述：
  =s.des 
  %br/
  创建于：
  =s.created_at
  %br/
  -if @isowner
    =link_to '添加心愿',{:controller=>'wishes',:action=>'new',:s=>s}
    =' | '
    =link_to '编辑', edit_space_url(s)
    =' | '
    =link_to '删除', s, :confirm => '确定删除？', :method => :delete
  %hr/
  



app/views/spaces/new.haml
%h1 创建空间

=render 'form'

= link_to '返回', user_spaces_url(session[:user_id])

app/views/spaces/show.haml
-content_for :rside do
  rside

=render 'share/header'
%p{'style'=>"margin:0px;"}
  =@space.created_at 
  创建

-if @is_allowed
  %p
    %b 空间介绍
    = @space.des
    %br/
    -if @isowner
      =link_to '修改空间', edit_space_url(@space)
      |
      =link_to '添加愿望', {:controller=>'wishes',:action=>'new',:s=>@space.id}
      |
      =link_to '返回我的空间',user_spaces_url(session[:user_id])

  -if @wishes
    -@wishes.each do |wish|
      =link_to wish.name,wish_url(wish)
      %br/
      -if wish.tags.present?
        -wish.tags.each do |tag|
          =link_to tag,tag_topics_url(:tag=>tag),:class=>'tag'
        %br
      =wish.created_at
      添加
      %br
      描述：
      =wish.des
      %br/
      -if wish.comments_counter>0
        =wish.comments_counter
        条评论
      -else
        还没有评论
      -if @isowner
        =link_to '编辑', edit_wish_path(wish)
        |
        =link_to '删除', wish, :confirm => '确定删除？', :method => :delete 
        %br/
      %hr      
  =render 'share/comments'
-else
  =render 'no_privacy'