config/routes.rb
MongoSrc::Application.routes.draw do

  match 'space/:s/wish/new' =>'wishes#new'
  
  get 'follow/fo/:id', :action=>'fo',:controller=>'follow'
  get 'follow/unfo/:id', :action=>'unfo',:controller=>'follow'
  get 'follow/fo_tag/:tag', :action=>'fo_tag', :controller=>'follow', :as=>'fo_tag'
  get 'follow/unfo_tag/:tag', :action=>'unfo_tag', :controller=>'follow',:as=>'unfo_tag'

  get "/public-timeline", :action=>'publictimeline',:controller=>'index',:as=>'publictimeline'
  
  delete '/timeline/:id',:controller=>'timeline', :action=>'del'

  get '/reg', :controller=>'user',:action=>'reg'
  match "auth/:provider/callback", :to => "user#auth_callback"  

  resources :wishes,:except=>:new do
    collection do
      post 'comment'
      delete 'comment'
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
    end
  end
  
  resources :users, :controller=>'user',:only=>[:create,:show] do 
    resources :spaces
    member do
    end
  end
  
  resources :spaces do
    collection do
      post 'comment'
      delete 'comment'
    end  
  end
  
  resources :topics, :except => [:destroy] do
    resources :replies, :except => [:destroy]
    collection do
      get 'tag/:tag', :action => 'tag', :as => :tag, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get 'mine', :action=>'mine',:as=>:mine
      get 'replied', :action=>'replied', :as=>:replied
      get 'marked', :action=>'marked', :as=>:marked
      get 'interested', :action=>'interested', :as=>:interested
    end
    
    member do
      get :mark
      get :unmark
    end
    
  end
  
  resources :replies
  
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end









  root :to => "index#index", :as=>'index'


end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    -if @page_title
      %title= @page_title+' 心愿空间'
    -else
      %title='心愿空间'
    =stylesheet_link_tag :all
    =javascript_include_tag :defaults
    =csrf_meta_tag
  %body
    #container
      #header
        #nav-items
          %ul
            %li=link_to "首页",index_url
            - if @logged
              %li=link_to "我的首页", user_url(session[:user_id])
              %li=link_to "我的愿望空间", :controller=>'spaces',:action=>'index',:user_id=>session[:user_id]
            %li=link_to "大家在做什么？", publictimeline_url
            %li=link_to '茶馆', topics_url
        #nav-user-info
          - if @logged
            =link_to @user_name,index_url
            =link_to "注销", logout_url,:method=>'delete'
          -else
            ='登陆'
            
        %br.clear
      #content
        .main
          - if flash[:success]
            .notification#success
              %span.close x
              %div= flash[:success]              
          - if flash[:error]
            .notification#error
              %span.close x
              %div= flash[:error]              
          - if flash[:notice]
            .notice.flash
              = flash[:notice]
              %span.close x
          =yield
        .rside
          =yield :rside
      %br.clear
      #footer
        ='联系我们 免责声明'
    =javascript_include_tag "http://v1.jiathis.com/code/jiathis_r.js?move=0&amp;uid=902227"